language: php

php:
  - 7.1

sudo: false

before_script:
  - composer self-update
  - cp roles/server/templates/symfony_parameters.yml app/config/parameters.yml
  - composer install --prefer-source --no-interaction --ignore-platform-reqs
  - printf "\n" | pecl install mongodb
  - phpenv rehash

script:
  - cd app; phpunit

notifications:
  email: false
#  irc:
#    channels:
#      - 'irc.esper.net#korobi'
#    template:
#      - '%{repository}#%{build_number} (%{branch} - %{commit}) %{author}: %{message} - %{build_url}'
#    on_failure: always
#    on_success: change
