services:
    korobi.command.log_cache_clear:
        class: Korobi\WebBundle\Console\LogCacheClearCommand
        tags:
            -  { name: console.command }

    korobi.command.log_cache_stats:
        class: Korobi\WebBundle\Console\LogCacheStatsCommand
        tags:
            -  { name: console.command }

    korobi.command.db_provision:
        class: Korobi\WebBundle\Console\MongoProvisionCommand
        tags:
            -  { name: console.command }

    korobi.command.maintenance:
        class: Korobi\WebBundle\Console\MaintenanceCommand
        tags:
            -  { name: console.command }
