services:
    korobi.command.stats_gen:
        class: Korobi\WebBundle\Console\StatsGeneration
        arguments:
            - @korobi.influx
        tags:
            -  { name: console.command }

    korobi.command.log_cache_clear:
        class: Korobi\WebBundle\Console\LogCacheClearCommand
        tags:
            -  { name: console.command }

    korobi.command.log_cache_stats:
        class: Korobi\WebBundle\Console\LogCacheStatsCommand
        tags:
            -  { name: console.command }
