services:
    korobi.controller.irc.channel.home:
        class: Korobi\WebBundle\Controller\Generic\IRC\Channel\ChannelHomeController
        parent: korobi.base_controller
    korobi.controller.irc.channel.log:
        class: Korobi\WebBundle\Controller\Generic\IRC\Channel\ChannelLogController
        parent: korobi.base_controller
    korobi.controller.irc.channel.command:
        class: Korobi\WebBundle\Controller\Generic\IRC\Channel\ChannelCommandController
        parent: korobi.base_controller
    korobi.controller.irc.channel.stat:
        class: Korobi\WebBundle\Controller\Generic\IRC\Channel\ChannelStatController
        parent: korobi.base_controller
    korobi.controller.irc.channel.ai:
        class: Korobi\WebBundle\Controller\Generic\IRC\Channel\ChannelAIController
        parent: korobi.base_controller
