# root node - everything should be nested
korobi_web:
    navigation:
        items:
            - title: home
              route: 'home'

            - title: networks
              route: 'networks'
              routes:
                  - networks
                  - network
                  - channel
                  - channel_command
                  - channel_log
                  - channel_log_date
                  - channel_log_tail
                  - channel_stat
                  - channel_game

            - title: docs
              route: 'https://docs.korobi.io/'
              external: true

            - title: about
              route: 'about'

            - title: admin
              route: 'admin_home'
              requires_admin: true

            - title: issues
              route: 'https://github.com/korobi/Korobi/issues'
              type: 'footer'
              external: true

            - title: revisions
              route: 'revisions'
              type: 'footer'

    homepage_excluded_channels:
       - channel: '#spigot'
         network: 'esper'
