# root node - everything should be nested
korobi_web:
    navigation:
        items:
            - title: Home
              route: 'home'

            - title: Networks
              route: 'networks'
              routes:
              - networks
              - network
              - channel
              - channel_admin
              - channel_commands
              - channel_logs
              - channel_logs_date
              - channel_logs_date_tail
              - channel_logs_tail
              - channel_stats

            - title: Docs
              route: 'docs_index'

            - title: Admin
              route: 'dummy'
              requires_admin: true

            - title: Issues
              route: 'https://github.com/korobi/Korobi/issues'
              type: 'footer'
              external: true

            - title: Revisions
              route: 'revisions'
              type: 'footer'
