################################################################
##                           NOTICE                           ##
################################################################
#                                                              #
#    ALL BASE ROUTES MUST COME BEFORE THE 'networks' ROUTE!    #
#                                                              #
################################################################
home:
    path: /
    defaults:
        _controller: korobi.controller.home:homeAction
kitty_images:
    path: /kitty/
    defaults:
        _controller: korobi.controller.kitty:homeAction
deploy:
    path: /deploy/
    defaults:
        _controller: korobi.controller.deploy:deployAction
deploy_view:
    path: /deploy/view/{id}/
    defaults:
        _controller: korobi.controller.deploy:viewAction
docs:
    path: /docs/{file}/
    defaults:
        _controller: korobi.controller.docs:renderAction
        file: index
revisions:
    path: /revisions/{repository}/
    defaults:
        _controller: korobi.controller.revisions:listAction
        repository: Web
theme_toggle:
    path: /theme/
    defaults:
        _controller: korobi.theme_controller:toggleAction
style_guide:
    path: /style-guide/
    defaults:
        _controller: korobi.controller.style_guide:displayAction
csp_report:
    path: /csp/report/
    defaults:
        _controller: korobi.controller.security:reportCspAction
    methods:  [POST]
unexpected_redirect:
    path: /unexpected-redirect/
    defaults:
        _controller: korobi.controller.security:showRedirectAction
# temporary
dummy:
    path: /dummy/
    defaults:
        _controller: korobi.controller.home:homeAction }
################################################################
##                           NOTICE                           ##
################################################################
#                                                              #
#    ALL BASE ROUTES MUST COME BEFORE THE 'networks' ROUTE!    #
#                                                              #
################################################################

# ------------------
# ---- Networks ----
# ------------------
networks:
    path: /networks/
    defaults:
        _controller: korobi.controller.network:networksAction
network:
    path: /{network}/
    defaults:
        _controller: korobi.controller.network:networkAction

# ------------------
# ---- Channels ----
# ------------------
channel:
    path: /{network}/{channel}/
    defaults:
        _controller: korobi.controller.channel_home:homeAction
channel_commands:
    path: /{network}/{channel}/commands/
    defaults:
        _controller: korobi.controller.channel_command:commandsAction
channel_logs:
    path: /{network}/{channel}/logs/
    defaults:
        _controller: korobi.controller.channel_log:logsAction
channel_logs_date:
    path: /{network}/{channel}/logs/{year}/{month}/{day}/
    defaults:
        _controller: korobi.controller.channel_log:logsAction
channel_logs_tail:
    path: /{network}/{channel}/logs/tail/{tail}/
    defaults:
        _controller: korobi.controller.channel_log:logsAction
        tail: 30
channel_stats:
    path: /{network}/{channel}/stats/
    defaults:
        _controller: korobi.controller.channel_stat:statsAction
channel_ai:
    path: /{network}/{channel}/ai/
    defaults:
        _controller: korobi.controller.channel_ai:listAction
channel_games:
    path: /{network}/{channel}/games/{gameId}/
    defaults:
        _controller: korobi.controller.channel_game:gameAction
