home:
    path: /
    defaults: { _controller: korobi.home_controller:homeAction }
dummy:
    path: /dummy
    defaults: { _controller: korobi.home_controller:homeAction }
deploy:
    path: /deploy
    defaults: { _controller: korobi.deploy_controller:deployAction }
