_core_generic:
    resource: '@KorobiWebBundle/Resources/config/routing/core/generic.yml'
_core_internal:
    resource: '@KorobiWebBundle/Resources/config/routing/core/internal.yml'

_irc_network:
    resource: '@KorobiWebBundle/Resources/config/routing/irc/network.yml'
_irc_channel:
    resource: '@KorobiWebBundle/Resources/config/routing/irc/channel.yml'
    prefix: /network/
_irc_legacy:
    resource: '@KorobiWebBundle/Resources/config/routing/irc/legacy.yml'
