_core_public:
    resource: '@KorobiWebBundle/Resources/config/routing/core/public.yml'
_core_private:
    resource: '@KorobiWebBundle/Resources/config/routing/core/private.yml'

_irc_network:
    resource: '@KorobiWebBundle/Resources/config/routing/irc/network.yml'
_irc_channel:
    resource: '@KorobiWebBundle/Resources/config/routing/irc/channel.yml'
