home:
    path: /
    defaults: { _controller: KorobiWebBundle:Home:home }
dummy:
    path: /dummy
    defaults: { _controller: KorobiWebBundle:Home:home }
deploy:
    path: /deploy
    defaults: { _controller: korobi.deploy_controller:deployAction }
theme_toggle:
    path: /theme
    defaults: { _controller: korobi.theme_controller:toggleAction }
