################################################################
##                           NOTICE                           ##
################################################################
#                                                              #
#    ALL BASE ROUTES MUST COME BEFORE THE 'networks' ROUTE!    #
#                                                              #
################################################################
home:
    path: /
    defaults: { _controller: korobi.controller.home:homeAction }
deploy:
    path: /deploy
    defaults: { _controller: korobi.deploy_controller:deployAction }
revisions:
    path: /revisions/{repository}
    defaults: { _controller: korobi.controller.revisions:listAction, repository: Web }
theme_toggle:
    path: /theme
    defaults: { _controller: korobi.theme_controller:toggleAction }
# temporary
dummy:
    path: /dummy
    defaults: { _controller: korobi.controller.home:homeAction }
################################################################
##                           NOTICE                           ##
################################################################
#                                                              #
#    ALL BASE ROUTES MUST COME BEFORE THE 'networks' ROUTE!    #
#                                                              #
################################################################

# ------------------
# ---- Networks ----
# ------------------
networks:
    path: /networks
    defaults: { _controller: korobi.controller.network:networksAction }
network:
    path: /{network}
    defaults: { _controller: korobi.controller.network:networkAction }

# ------------------
# ---- Channels ----
# ------------------
channel:
    path: /{network}/{channel}
    defaults: { _controller: korobi.controller.channel:homeAction }
channel_admin:
    path: /{network}/{channel}/admin
    defaults: { _controller: korobi.controller.channel_admin:homeAction }
channel_commands:
    path: /{network}/{channel}/commands
    defaults: { _controller: korobi.controller.channel:commandsAction }
channel_logs:
    path: /{network}/{channel}/log
    defaults: { _controller: korobi.controller.channel:logsAction }
channel_logs_date:
    path: /{network}/{channel}/logs/{year}/{month}/{day}
    defaults: { _controller: korobi.controller.channel:logsAction }
channel_logs_date_tail:
    path: /{network}/{channel}/logs/{year}/{month}/{day}/tail/{tail}
    defaults: { _controller: korobi.controller.channel:logsAction, tail: 30 }
channel_logs_tail:
    path: /{network}/{channel}/logs/tail/{tail}
    defaults: { _controller: korobi.controller.channel:logsAction, tail: 30 }
channel_stats:
    path: /{network}/{channel}/stats
    defaults: { _controller: korobi.controller.channel_stats:statsAction }
