home:
    path: /
    defaults: { _controller: KorobiWebBundle:Home:home }
logs:
    path: /logs
    defaults: { _controller: KorobiWebBundle:Log:home }
logs_network:
    path: /logs/{network}
    defaults: { _controller: KorobiWebBundle:Log:network }
logs_channel:
    path: /logs/{network}/{channel}
    defaults: { _controller: KorobiWebBundle:Log:channel }

dummy:
    path: /dummy
    defaults: { _controller: KorobiWebBundle:Home:home }
revisions:
    path: /revisions
    defaults: { _controller: KorobiWebBundle:Revisions:list }
deploy:
    path: /deploy
    defaults: { _controller: korobi.deploy_controller:deployAction }
theme_toggle:
    path: /theme
    defaults: { _controller: korobi.theme_controller:toggleAction }
