home:
    path: /
    defaults: { _controller: KorobiWebBundle:Home:home }

# ----------------------
# ---- Channel Logs ----
# ----------------------
# network list
logs:
    path: /logs
    defaults: { _controller: KorobiWebBundle:Log:home }
# channel list
logs_network:
    path: /logs/{network}
    defaults: { _controller: KorobiWebBundle:Log:network }
# channel
logs_channel:
    path: /logs/{network}/{channel}
    defaults: { _controller: KorobiWebBundle:Log:channel }
# channel by date
logs_channel_date:
    path: /logs/{network}/{channel}/{year}/{month}/{day}
    defaults: { _controller: KorobiWebBundle:Log:channel }
# channel by date with tail
logs_channel_date_tail:
    path: /logs/{network}/{channel}/{year}/{month}/{day}/tail/{tail}
    defaults: { _controller: KorobiWebBundle:Log:channel, tail: 30 }
# channel with tail
logs_channel_tail:
    path: /logs/{network}/{channel}/tail/{tail}
    defaults: { _controller: KorobiWebBundle:Log:channel, tail: 30 }

dummy:
    path: /dummy
    defaults: { _controller: KorobiWebBundle:Home:home }
revisions:
    path: /revisions
    defaults: { _controller: KorobiWebBundle:Revisions:list }
deploy:
    path: /deploy
    defaults: { _controller: korobi.deploy_controller:deployAction }
theme_toggle:
    path: /theme
    defaults: { _controller: korobi.theme_controller:toggleAction }
