services:
    # twig services
    korobi.extension.twig.globals:
        class: Korobi\WebBundle\Extension\ExtensionTwigGlobals
        tags:
            - { name: twig.extension }
        arguments: [%kernel.root_dir%]

    # controllers
    korobi.base_controller:
        class: Korobi\WebBundle\Controller\BaseController
        calls:
            - [setContainer, ["@service_container"]]
            - [setAuthChecker, ["@security.authorization_checker"]]
    korobi.deploy_controller:
        class: Korobi\WebBundle\Controller\DeploymentController
        parent: korobi.base_controller
        arguments:
            - @logger
            - @korobi.git_info
        calls:
            - [setHmacKey, ["%github_hook_hmac_secret%"]]
            - [setRootPath, ["%kernel.root_dir%"]]
    korobi.theme_controller:
        class: Korobi\WebBundle\Controller\ThemeController
        parent: korobi.base_controller
        arguments:
            - @session

    # database
    korobi.channel_repository:
        class: Korobi\WebBundle\Repository\ChannelRepository
        factory_service: doctrine_mongodb
        factory_method: getRepository
        public: false
        arguments:
           - "KorobiWebBundle:Channel"

    # helpers
    korobi.git_info:
        class: Korobi\WebBundle\Util\GitInfo
    korobi.navigation_collection:
        class: Korobi\WebBundle\Util\NavigationCollection
        arguments:
            - %korobi.config%
    korobi.theme_service:
        class: Korobi\WebBundle\Util\ThemeService
        arguments:
            - @session
