services:
    # -------------------------
    # ---- Twig Extensions ----
    # -------------------------
    korobi.extension.twig.globals:
        class: Korobi\WebBundle\Extension\ExtensionTwigGlobals
        tags:
            - { name: twig.extension }
    korobi.extension.twig.filters:
        class: Korobi\WebBundle\Extension\ExtensionTwigFilters
        tags:
            - { name: twig.extension }

    # ---------------------
    # ---- Controllers ----
    # ---------------------
    korobi.base_controller:
        class: Korobi\WebBundle\Controller\BaseController
        calls:
            - [setContainer, ["@service_container"]]
            - [setAuthChecker, ["@security.authorization_checker"]]
    korobi.controller.home:
        class: Korobi\WebBundle\Controller\HomeController
        parent: korobi.base_controller
    korobi.controller.network:
        class: Korobi\WebBundle\Controller\NetworkController
        parent: korobi.base_controller
    korobi.controller.channel:
        class: Korobi\WebBundle\Controller\ChannelController
        parent: korobi.base_controller
    korobi.controller.revisions:
        class: Korobi\WebBundle\Controller\RevisionsController
        parent: korobi.base_controller
    korobi.deploy_controller:
        class: Korobi\WebBundle\Controller\DeploymentController
        parent: korobi.base_controller
        arguments:
            - @logger
            - @korobi.git_info
            - @korobi.akio
        calls:
            - [setHmacKey, ["%github_hook_hmac_secret%"]]
            - [setRootPath, ["%kernel.root_dir%"]]
    korobi.theme_controller:
        class: Korobi\WebBundle\Controller\ThemeController
        parent: korobi.base_controller
        arguments:
            - @session

    # ---------------------------
    # ---- Helpers/Utilities ----
    # ---------------------------
    korobi.git_info:
        class: Korobi\WebBundle\Util\GitInfo
    korobi.navigation_collection:
        class: Korobi\WebBundle\Util\NavigationCollection
        arguments:
            - %korobi.config%
    korobi.theme_service:
        class: Korobi\WebBundle\Util\ThemeService
        arguments:
            - @session
    korobi.akio:
        class: Korobi\WebBundle\Util\Akio
        arguments:
            - %akio_path%
            - %akio_key%
