services:
    korobi.extension.twig.globals:
        class: Korobi\WebBundle\Extension\ExtensionTwigGlobals
        tags:
            - { name: twig.extension }
        arguments: [%kernel.root_dir%]

    korobi.home_controller:
        class: Korobi\WebBundle\Controller\HomeController
        arguments:
          - @templating
          - @korobi.channel_repository

    korobi.deploy_controller:
        class: Korobi\WebBundle\Controller\DeploymentController
        arguments:
          - @templating
          - @logger
        calls:
          - [setHmacKey, [" %github_hook_hmac_sec"]]

    korobi.channel_repository:
        class: Korobi\WebBundle\Repository\ChannelRepository
        factory_service: doctrine_mongodb
        factory_method: getRepository
        public: false
        arguments:
            - "KorobiWebBundle:Channel"
