services:
    # -------------------------
    # ---- Twig Extensions ----
    # -------------------------
    korobi.extension.twig.globals:
        class: Korobi\WebBundle\Extension\ExtensionTwigGlobals
        tags:
            - { name: twig.extension }
        arguments:
            - @korobi.git_info
    korobi.extension.twig.filters:
        class: Korobi\WebBundle\Extension\ExtensionTwigFilters
        tags:
            - { name: twig.extension }
    korobi.extension.twig.functions:
        class: Korobi\WebBundle\Extension\ExtensionTwigFunctions
        tags:
            - { name: twig.extension }
    salavert.twig.time_ago:
        class: Salavert\Twig\Extension\TimeAgoExtension
        arguments: [@translator]
        tags:
          - { name: twig.extension }

    # ---------------------
    # ---- Controllers ----
    # ---------------------
    korobi.base_controller:
        class: Korobi\WebBundle\Controller\BaseController
        calls:
            - [setContainer, ["@service_container"]]
            - [setAuthChecker, ["@security.authorization_checker"]]
    # Public
    korobi.controller.home:
        class: Korobi\WebBundle\Controller\Generic\HomeController
        parent: korobi.base_controller
    korobi.controller.kitty:
        class: Korobi\WebBundle\Controller\Generic\KittyImageController
        parent: korobi.base_controller
    korobi.controller.revisions:
        class: Korobi\WebBundle\Controller\Generic\RevisionsController
        parent: korobi.base_controller
    korobi.controller.docs:
        class: Korobi\WebBundle\Controller\Generic\DocsController
        parent: korobi.base_controller
    korobi.controller.style_guide:
        class: Korobi\WebBundle\Controller\Generic\StyleGuideController
        parent: korobi.base_controller
    korobi.controller.security:
        class: Korobi\WebBundle\Controller\Generic\SecurityController
        parent: korobi.base_controller
        arguments:
            - @korobi.akio
            - @logger
    # Private
    korobi.controller.deploy:
        class: Korobi\WebBundle\Controller\Internal\DeploymentController
        parent: korobi.base_controller
        arguments:
            - @logger
            - @korobi.git_info
            - @korobi.akio
        calls:
            - [setHmacKey, ["%github_hook_hmac_secret%"]]
            - [setRootPath, ["%kernel.root_dir%"]]
    # Network
    korobi.controller.network.home:
        class: Korobi\WebBundle\Controller\Generic\IRC\Network\NetworkHomeController
        parent: korobi.base_controller
    # Channel
    korobi.controller.channel.home:
        class: Korobi\WebBundle\Controller\Generic\IRC\Channel\ChannelHomeController
        parent: korobi.base_controller
    korobi.controller.channel.log:
        class: Korobi\WebBundle\Controller\Generic\IRC\Channel\ChannelLogController
        parent: korobi.base_controller
    korobi.controller.channel.command:
        class: Korobi\WebBundle\Controller\Generic\IRC\Channel\ChannelCommandController
        parent: korobi.base_controller
    korobi.controller.channel.stat:
        class: Korobi\WebBundle\Controller\Generic\IRC\Channel\ChannelStatController
        parent: korobi.base_controller
    korobi.controller.channel.ai:
        class: Korobi\WebBundle\Controller\Generic\IRC\Channel\ChannelAIController
        parent: korobi.base_controller
    korobi.controller.channel.game:
        class: Korobi\WebBundle\Controller\Generic\IRC\Channel\ChannelGameController
        parent: korobi.base_controller
    # Legacy
    korobi.controller.rewrite:
        class: Korobi\WebBundle\Controller\RewriteController
        parent: korobi.base_controller

    # ---------------------------
    # ---- Helpers/Utilities ----
    # ---------------------------
    korobi.git_info:
        class: Korobi\WebBundle\Util\GitInfo
    korobi.navigation_collection:
        class: Korobi\WebBundle\Util\NavigationCollection
        arguments:
            - %korobi.config%
    korobi.akio:
        class: Korobi\WebBundle\Util\Akio
        arguments:
            - %akio_enabled%
            - %akio_path%
            - %akio_key%
    korobi.influx:
        class: Korobi\WebBundle\Util\InfluxService
        arguments:
            - %influx_host%
            - %influx_port%
            - %influx_user%
            - %influx_pass%
            - %influx_db%

    # ----------------------------
    # ----- Console commands -----
    # ----------------------------
    korobi.command.stats_gen:
        class: Korobi\WebBundle\Console\StatsGeneration
        arguments:
            - @korobi.influx
        tags:
            -  { name: console.command }
