# ------------------------
# ---- Network Routes ----
# ------------------------
networks:
    path: /networks/
    defaults:
        _controller: korobi.controller.network:networksAction
network:
    path: /{network}/
    defaults:
        _controller: korobi.controller.network:networkAction
