# ------------------------
# ---- Network Routes ----
# ------------------------
networks:
    path: /networks/
    defaults:
        _controller: korobi.controller.irc.network.home:networksAction
network:
    path: /network/{network}/
    defaults:
        _controller: korobi.controller.irc.network.home:networkAction
