# -----------------------
# ---- Public Routes ----
# -----------------------
home:
    path: /
    defaults:
        _controller: korobi.controller.home:homeAction
docs:
    path: /docs/
    defaults:
        _controller: korobi.controller.docs:renderAction
        file: index
docs_file:
    path: /docs/{file}/
    defaults:
        _controller: korobi.controller.docs:renderAction
        file: index
kitty_images:
    path: /kitty/
    defaults:
        _controller: korobi.controller.kitty:homeAction
revisions:
    path: /revisions/{repository}/
    defaults:
        _controller: korobi.controller.revisions:listAction
        repository: Web
theme_toggle:
    path: /theme/
    defaults:
        _controller: korobi.theme_controller:toggleAction
style_guide:
    path: /style-guide/
    defaults:
        _controller: korobi.controller.style_guide:displayAction
csp_report:
    path: /csp/report/
    defaults:
        _controller: korobi.controller.security:reportCspAction
    methods: [POST]
unexpected_redirect:
    path: /unexpected-redirect/
    defaults:
        _controller: korobi.controller.security:showRedirectAction
# temporary
dummy:
    path: /dummy/
    defaults:
        _controller: korobi.controller.home:homeAction
