# -----------------------
# ---- Public Routes ----
# -----------------------
home:
    path: /
    defaults:
        _controller: korobi.controller.generic.home:homeAction
about:
    path: /about/
    defaults:
        _controller: korobi.controller.generic.about:homeAction
csp_report:
    path: /csp/report/
    defaults:
        _controller: korobi.controller.generic.security:reportCspAction
    methods: [POST]
analytics_script:
    path: /dynamic/analytics/
    defaults:
        _controller: korobi.controller.generic.security:safelyReturnScriptSource
docs:
    path: /docs/
    defaults:
        _controller: korobi.controller.generic.docs:renderAction
        file: index
docs_file:
    path: /docs/{file}/
    defaults:
        _controller: korobi.controller.generic.docs:renderAction
        file: index
kitty_images:
    path: /kitty/
    defaults:
        _controller: korobi.controller.generic.kitty:homeAction
revisions:
    path: /revisions/{repository}/
    defaults:
        _controller: korobi.controller.generic.revisions:listAction
        repository: Web
style_guide:
    path: /style-guide/
    defaults:
        _controller: korobi.controller.generic.style_guide:displayAction
unexpected_redirect:
    path: /unexpected-redirect/
    defaults:
        _controller: korobi.controller.generic.security:showRedirectAction
# temporary
dummy:
    path: /dummy/
    defaults:
        _controller: korobi.controller.generic.home:homeAction
