# ------------------------
# ---- Private Routes ----
# ------------------------
deploy:
    path: /deploy/
    defaults:
        _controller: korobi.controller.internal.deploy:deployAction
deploy_view:
    path: /deploy/view/{id}/
    defaults:
        _controller: korobi.controller.internal.deploy:viewAction
