---
- name: allocate swap
  command: /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
  args:
    creates: /var/swap.1
  register: swap

- name: make swap
  command: /sbin/mkswap /var/swap.1
  when: swap.changed

- name: enable swap
  command: /sbin/swapon /var/swap.1
  when: swap.changed
