Korobi\WebBundle\Entity\ChannelViewKey:
    type: entity
    table: channel_view_keys
    repositoryClass: Korobi\WebBundle\Entity\ChannelViewKeyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        network:
            type: string
            length: 255
        channel:
            type: string
            length: 255
        viewKey:
            type: string
            length: 255
            column: view_key
    lifecycleCallbacks: {  }
